# Generated by Django 5.0.6 on 2024-06-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_schools'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_purchase_access_key', 'Can purchase access key'), ('can_revoke_access_key', 'Can revoke access key')]},
        ),
    ]
