# Generated by Django 5.0.6 on 2024-06-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_schools'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
