# Generated by Django 5.0.6 on 2024-07-18 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_add_schools'),
        ('users', '0002_add_schools'),
    ]

    operations = [
    ]
