# Generated by Django 5.0.6 on 2024-06-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_completed',
        ),
        migrations.AlterField(
            model_name='billinginformation',
            name='payment_method',
            field=models.CharField(choices=[('MTN MOMO', 'MTN Mobile Money'), ('Card', 'Credit/Debit Card')], max_length=10),
        ),
    ]
