# Generated by Django 5.0.6 on 2024-06-02 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_school'),
        ('users', '0004_add_schools'),
    ]

    operations = [
    ]
