# Generated by Django 5.0.6 on 2024-06-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_0003_alter_user_school_0004_add_schools'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billinginformation',
            old_name='credit_card_number',
            new_name='card_number',
        ),
        migrations.AlterField(
            model_name='billinginformation',
            name='payment_method',
            field=models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('Card', 'Credit/Debit Card')], max_length=10),
        ),
    ]
