# Generated by Django 5.0.6 on 2024-06-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_profile_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginformation',
            name='payment_method',
            field=models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('card', 'Credit/Debit Card')], max_length=10),
        ),
    ]
