# Generated by Django 5.0.6 on 2024-06-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_billinginformation_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginformation',
            name='card_expiry',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
