# Generated by Django 5.0.6 on 2024-06-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_credit_card_number_billinginformation_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginformation',
            name='mobile_money_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
