# Generated by Django 5.0.6 on 2024-06-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_billinginformation_card_expiry'),
        ('users', '0008_add_schools'),
    ]

    operations = [
    ]
