# Generated by Django 5.0.6 on 2024-06-04 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_billinginformation_mobile_money_number'),
        ('users', '0008_add_schools'),
    ]

    operations = [
    ]
