# Generated by Django 5.0.6 on 2024-06-25 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_staff_id'),
        ('users', '0011_add_schools'),
    ]

    operations = [
    ]
