# Generated by Django 5.0.6 on 2024-06-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_email'),
        ('users', '0014_add_schools'),
    ]

    operations = [
    ]
