# Generated by Django 5.0.6 on 2024-06-26 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_0013_alter_user_email_0014_add_schools'),
        ('users', '0016_add_schools'),
    ]

    operations = [
    ]
