# Generated by Django 5.0.6 on 2024-07-14 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_merge_20240626_2202'),
        ('users', '0018_add_schools'),
    ]

    operations = [
    ]
