services:
  - type: web
    name: mfocusmanager
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: supervisord -c Supervisord.conf
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: access-key-manager-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: mfocus-redis
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: access_key_manager.settings
    postdeploy:
      - python manage.py migrate

databases:
  - name: mfocus-manager-db
    plan: free

redis:
  - name: mfocus-redis
    plan: free
