services:
  - type: web
    name: access-key-manager
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn access_key_manager.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: access_key_manager.settings
    postdeploy:
      - python manage.py migrate
      - python manage.py assign_permissions
