# Generated by Django 5.0.6 on 2024-05-15 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_keys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesskey',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revokedaccesskey',
            name='access_key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='access_keys.accesskey'),
        ),
        migrations.AddField(
            model_name='revokedaccesskey',
            name='revoked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesskey',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access_keys.school'),
        ),
    ]
