# Generated by Django 5.0.6 on 2024-06-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_keys', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskey',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='procurement_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
