# Generated by Django 5.0.6 on 2024-06-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_keys', '0003_accesskey_assigned_to_alter_accesskey_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesskey',
            old_name='revoked_at',
            new_name='revoked_on',
        ),
    ]
