# Generated by Django 5.0.6 on 2024-06-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_keys', '0004_rename_revoked_at_accesskey_revoked_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesskey',
            name='purchased',
        ),
    ]
